# Write Functions with Multiple Parameters in Python

## Write a function with multiple parameters in Python

In [5]:
def multiply_values(x, y):
    '''
    Calculate product of 2 inputs.
    
    Parameters
    ----------
    x: int or float
    y: int or float
    
    Returns
    -------
    z: int or float
    '''
    z = x*y
    return z

## Call custom functions with multiple parameters in Python

Now that you have defined the function multiple_values(), you can call it by providing values for the 2 input parameters.

In [6]:
# Call function with numeric values
multiply_values(x = 0.7, y = 25.4)

17.779999999999998

Recall that you can also provide pre-defined variables as input, for example, a value for precipitation and another value for a unit conversion value.

In [7]:
# Average monthly precip (inches) for Jan in Boulder, CO
precip_jan_in = 0.7

# Conversion factor from inches to mm
to_mm = 25.4

# Call function with pre-defined variables
precip_jan_mm = multiply_values(
    x = precip_jan_in,
    y = to_mm)

precip_jan_mm

17.779999999999998

##  Combine unit conversion and calculation of stats into 1 function

Imagine that you want to both convert the unit of a numpy array from mm to inches and calculate the mean value along a specified axis for either columns or rows.

In [8]:
def mm_to_in(mm):
    '''
    Convert input from mm to inches.
    
    Parameters
    -----------
    mm: int or flaot
        Numeric value with units in mm.
    
    Returns
    --------
    inches: int or float
        Numeric value with units in inches.
    '''
    inches = mm/25.4
    return inches

You can expand this function to include running a mean along a specified axis for columns or rows, and then use this function over and over on many numpy arrays as needed.

This new function can have descriptive names for the function and the input parameters that describe more clearly what the function accomplishes.

Begin by defining the function with a descriptive name and the 2 necessary parameters:
- the input array with values in mm
- the axis value for the mean calc

Use placeholder variable names that highlight the purpose of each parmeter:

In [10]:
def mean_mm_to_in_arr(arr_mm, axis_value):
    '''
    Calculate mean values of input array along a specified
    axis and convert values from mm to inches.
    
    Parameters
    -----------
    arr_mm: numpy array
        Numeric values in mm.
    axis_value: int
        0 to calculate mean for each column.
        1 to calculate mean for each row.
        
    Returns
    --------
    mean_arr_in: numpy array
        Mean values of input array in inches.
    '''
    mean_arr_mm = np.mean(arr_mm, axis = axis_value)
    mean_arr_in = mean_arr_mm/25.4
    return mean_arr_in

Create some data and test your new function with different input values for the axis_value parameter.

In [11]:
# Import necessary package to run function
import numpy as np

# 2D array of average monthly precip (mm) for 2002 and 2013 in Boulder, CO
precip_2002_2013_mm = np.array([[27.178, 11.176, 38.1, 5.08, 81.28, 29.972, 
                                 2.286, 36.576, 38.608, 61.976, 19.812, 0.508],
                                [6.858, 28.702, 43.688, 105.156, 67.564, 15.494,  
                                 26.162, 35.56 , 461.264, 56.896, 7.366, 12.7]
                               ])

# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm,
                                   axis_value = 0)

monthly_mean_in

array([0.67 , 0.785, 1.61 , 2.17 , 2.93 , 0.895, 0.56 , 1.42 , 9.84 ,
       2.34 , 0.535, 0.26 ])

In [12]:
# Calculate yedarly mean (inches) for precip_2002_2013
yearly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm,
                                  axis_value = 1)

yearly_mean_in

array([1.15666667, 2.84583333])

## Define optional input parameters for a function

Your previously defined function works well if you want to use a specified axis for the mean.

However, notice what happens when you try to call the function without providing an axis value, such as for a 1D array.

In [16]:
# 1D array of average monthly precip (mm) for 2002 in Boulder, CO
precip_2002_mm = np.array([27.178, 11.176, 38.1, 5.08, 81.28, 29.972,
                          2.286, 36.576, 38.608, 61.976, 19.812, 0.508])

    # Calculate mean (inches) for precip_2002
    monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_mm)

IndentationError: unexpected indent (<ipython-input-16-099f96a33e2b>, line 6)

What if you want to make the function more generalisable, so that the axis value is optional?

You can do that by specifying a default value for axis_value as None as shown below:

In [19]:
def mean_mm_to_in_arr(arr_mm, axis_value=None):
    '''
    Calculate meaqn values of input array and convert values
    from millimeters to inches. If an axis is specified,
    the mean will be calculated along that axis.
    
    Parameters
    -----------
    arr_mm: numpy array
        Numeric values in mm.
    axis_value: int (optioonal)
        0 to calculate mean for each column
        1 to calculate mean for each row
    
    Returns
    -------
    mean_arr_in: numpy array
        Mean values of input array in inches.
    '''
    if axis_value is None:
        mean_arr_mm = np.mean(arr_mm)
    else:
        mean_arr_mm = np.mean(arr_mm, axis = axis_value)
    
    mean_arr_in = mean_arr_mm / 25.4
    
    return mean_arr_in

Notice that the function will return the same output as before the 2D array precip_2002_2013_mm.

In [20]:
# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm,
                                   axis_value = 0)

monthly_mean_in

array([0.67 , 0.785, 1.61 , 2.17 , 2.93 , 0.895, 0.56 , 1.42 , 9.84 ,
       2.34 , 0.535, 0.26 ])

However, now you can also provide a 1D array as an input without a specified axis anhd receive the appropriate output.

In [21]:
# Calculate mean (inches) for precip_2002
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_mm)

monthly_mean_in

1.606220472440945

## Combine download and import of data files into 1 function

You can alos write multi-parameter functions to combine other tasks into 1 function, such as downloading and importing data files into a pandas dataframe.

Think about the code that you need to include in the function:
1. download data file from URL: et.data.get_data(url=file_url)
2. import data file into pandas dataframe: pd.read_csv(path)

From this code, you can see that you will need 2 input parameters for the combined function:
1. the URL to the data file
2. the path to the downloaded file

In [5]:
def download_import_df(file_url, path):
    '''
    Download file from specified URL and import file
    into a pandas dataframe from a specified path.
    
    Working directory is set to earth-analytics directory
    under home, which is automatically created by the
    download.
    
    Parameters
    ----------
    file_url: str
        URL to CSV file (http or https).
    path: str
        Path to CSV file using relative path
        to earth-analytics directory under home.
        
    Returns
    -------
    df: pandas dataframe
        Dataframe imported from downloaded CSV file.
    '''
    et.data.get_data(url=file_url)
    os-chdir(os.path.join(et.io.HOME, "earth-analytics"))
    df = pd.read_csv(path)
    
    return df

Now that you have defined the function, you can import the packages needed to run the function and define the variables that you will use as input parameters

In [6]:
import os
import pandas as pd
import earthpy as et

# URL for average monthly precip (inches) for 2002 and 2013 in Boulder, CO
precip_2002_2013_df_url = "https://ndownloader.figshare.com/files/12710621"

# Path to downloaded .csv file with headers
precip_2002_2013_df_path = os.path.join("data", "earthpy-downloads",
                                       "precip-2002-2013-months-seasons.csv")

In [11]:
# Create dataframe using download/import function
precip_2002_2013_df = download_import_df(
    file_url = precip_2002_2013_df_url,
    path = precip_2002_2013_df_path)

precip_2002_2013_df

NameError: name 'chdir' is not defined

### Making functions more efficient does not always mean more parameters

Note that you previously defined download_import_df() to take in 2 parameters, 1 for the URL and for the path, and the function works well to accomplish the task.

However, with a little investigation into the et.data.get_data() function, you can see that the output of that function is actually a path to the downloaded file!

In [12]:
help(et.data.get_data)

Help on method get_data in module earthpy.io:

get_data(key=None, url=None, replace=False, verbose=True) method of earthpy.io.Data instance
    Retrieve the data for a given week and return its path.
    
    This will retrieve data from the internet if it isn't already
    downloaded, otherwise it will only return a path to that dataset.
    
    Parameters
    ----------
    key : str
        The dataset to retrieve. Possible options can be found in
        ``self.data_keys``. Note: ``key`` and ``url`` are mutually
        exclusive.
    url : str
        A URL to fetch into the data directory. Use this for ad-hoc dataset
        downloads. Note: ``key`` and ``url`` are mutually exclusive.
    replace : bool
        Whether to replace the data for this key if it is
        already downloaded.
    verbose : bool
        Whether to print verbose output while downloading files.
    
    Returns
    -------
    path_data : str
        The path to the downloaded data.
    
    Examples
  

In the docstring details provided, you can see that the full path to the downloaded data is returned by the function:

This means that you can redefine download_import_df() to be more efficient by simply using the output of the et.data.get_data() fuznction as the input to the pd.read_csv() function.

Now, you actually only need 1 parameter for the URL and you do not have to define the working directory in the function, in order to find the appropriate file.

In [19]:
def download_import_df(file_url):
    '''
    Download file from specified URL and import file
    injto a pandas dataframe.
    
    The path to the download file is auto gen
    by the download and is passed to the pandas
    function to create a new dataframe.
    
    Parameters
    -----------
    file url: str
        URL to CSV file (http or https).
    
    Returns
    --------
    df: pandas dataframe
        DataFrame imported from downloaded CSV file.
    '''
    
    df = pd.read_csv(et.data.get_data(url=file_url))
    
    return df

In [21]:
# Create dataframe using download/import function
precip_2002_2013_df = download_import_df(
    file_url = precip_2002_2013_df_url)

precip_2002_2013_df

months  precip_2002  precip_2013 seasons
0     Jan         1.07         0.27  Winter
1     Feb         0.44         1.13  Winter
2     Mar         1.50         1.72  Spring
3     Apr         0.20         4.14  Spring
4     May         3.20         2.66  Spring
5    June         1.18         0.61  Summer
6    July         0.09         1.03  Summer
7     Aug         1.44         1.40  Summer
8    Sept         1.52        18.16    Fall
9     Oct         2.44         2.24    Fall
10    Nov         0.78         0.29    Fall
11    Dec         0.02         0.50  Winter